from idlelib.filelist import FileList
from tkinter import Misc
from typing import Any

def isAquaTk() -> bool: ...
def isCarbonTk() -> bool: ...
def isCocoaTk() -> bool: ...
def isXQuartz() -> bool: ...
def readSystemPreferences() -> dict[str, Any] | None: ...
def preferTabsPreferenceWarning() -> str | None: ...
def addOpenEventSupport(root: Misc, flist: FileList) -> None: ...
def hideTkConsole(root: Misc) -> None: ...
def overrideRootMenu(root: Misc, flist: FileList) -> None: ...
def fixb2context(root: Misc) -> None: ...
def setupApp(root: Misc, flist: FileList) -> None: ...
