from idlelib.pyshell import PyShellEditorWindow
from tkinter import Event, Misc
from typing import Any

class WmInfoGatheringError(Exception): ...

class ZoomHeight:
    editwin: PyShellEditorWindow
    top: Misc
    def __init__(self, editwin: PyShellEditorWindow) -> None: ...
    def zoom_height_event(self, event: Event[Any] | None = ...) -> str: ...
    def zoom_height(self) -> bool | None: ...
    def get_max_height_and_y_coord(self) -> int: ...

def get_window_geometry(top: Misc) -> tuple[int, int, int, int]: ...
def set_window_geometry(
    top: Misc,
    geometry: tuple[int, int, int, int],
) -> None: ...
